Insere Dupla KELLY_LUCAS
gustavopinto/tesl pull request #1
Opened 2019-04-01 14:43 UTC by souzaluuk

2019-04-01 17:05 UTC, gustavopinto requested changes
Olá, 

antes de aceitar o PR, por favor, corrija os itens apontados na revisão.

Gustavo

2019-04-01 17:05 UTC, gustavopinto commented on duplas/Dupla_KELLY_LUCAS.md
> +- Atividade01: [link aqui](#)
Falta o link para a atividade da última aula.

2019-04-01 17:05 UTC, gustavopinto commented on duplas/Dupla_KELLY_LUCAS.md
> +# Dupla KELLY e LUCAS
Nome da dupla deve estar em bullet.

2019-04-01 17:05 UTC, gustavopinto commented on Duplas.md
> +## Dupla KELLY_LUCAS
Este é somente um arquivo de template, e não deve ser modificado.

2019-04-03 13:56 UTC, souzaluuk commented on Duplas.md
> +## Dupla KELLY_LUCAS
Pelo que li no seu último commit, devo fazer um link em `KELLY_LUCAS` para o arquivo criado na pasta `duplas` (Dupla_KELLY_LUCAS.md).
Estou certo?

2019-04-03 13:58 UTC, souzaluuk commented on duplas/Dupla_KELLY_LUCAS.md
> +# Dupla KELLY e LUCAS
Seria repetir o conteúdo do arquivo `Duplas.md` assim:
> - Kelly do Socorro Silva da Costa (kellydosocorro@gmail.com, [@kellydosocorro](https://github.com/kellydosocorro))
> - Lucas Gabriel de Souza (lucassouzaufpa@gmail.com, [@souzaluuk](https://github.com/souzaluuk))

2019-04-04 02:34 UTC, souzaluuk commented
As mudanças resolvem?

2019-04-04 13:22 UTC, gustavopinto approved these changes
Resolvem. Obrigado.

2019-04-04 13:22 UTC, gustavopinto commented on duplas/Dupla_KELLY_LUCAS.md
> +# Dupla KELLY e LUCAS
Isso mesmo

2019-04-04 13:25 UTC, merged