Update CAIO_LEONARDO w/ Atividade07 (Aula08)
gustavopinto/tesl pull request #105
Opened 2019-05-17 20:55 UTC by CaioSR

2019-05-24 18:28 UTC, filipesaraiva requested changes

2019-05-24 18:28 UTC, filipesaraiva commented on duplas/Dupla_CAIO_LEONARDO.md
> +### - Atividade07 (Aula 08.md)
Aparentemente hã 2 atividades realizadas, faltando portanto 1.

2019-05-24 18:28 UTC, filipesaraiva commented on duplas/Dupla_CAIO_LEONARDO.md
>  - Atividade05: [link aqui](https://docs.google.com/document/d/1OJC4tPS-wKc1dyBgXqeB0EW4DIO4p8uDfMZCxs7g4Cg/edit?usp=sharing)
Colocar o conteúdo dessas atividades diretamente no arquivo, e não mais em documentos externos no docs.

2019-05-24 18:42 UTC, filipesaraiva commented on duplas/Dupla_CAIO_LEONARDO.md
> +### - Atividade07 (Aula 08.md)
Essa parte está ok.

2019-05-24 22:55 UTC, CaioSR commented on duplas/Dupla_CAIO_LEONARDO.md
>  - Atividade05: [link aqui](https://docs.google.com/document/d/1OJC4tPS-wKc1dyBgXqeB0EW4DIO4p8uDfMZCxs7g4Cg/edit?usp=sharing)
Pronto.

2019-05-24 22:58 UTC, CaioSR commented on duplas/Dupla_CAIO_LEONARDO.md
> +### - Atividade07 (Aula 08.md)
Tem 3 professor. Definição do Linter (1), boas práticas para linguagens (2), e boas práticas para frameworks (3).

2019-05-31 19:18 UTC, filipesaraiva approved these changes

2019-05-31 19:22 UTC, merged