Arquivo para trabalho final
gustavopinto/tesl pull request #137
Opened 2019-06-07 15:09 UTC by juliocesark

Criação do arquivo para o trabalho final.

2019-06-19 13:56 UTC, gustavopinto commented
oi @juliocesark, 

para o trabalho final, foi pedido aos alunos para abrir uma issue descrevendo o que será feito. Você pode abrir uma, descrevendo seu trabalho e o que já foi feito nesse PR?

Gustavo

2019-07-01 17:18 UTC, filipesaraiva requested changes

2019-07-01 17:18 UTC, filipesaraiva commented on trabalho-final/JulioCesar.md
> +* Adicionado uma pequena funcionalidade com o repositório [bootstrap-social](https://github.com/lipis/bootstrap-social) referente a redes sociais no projeto calourada-bootstrap ([calourada-bootstrap#
Descrever melhor que funcionalidade foi adicionada. Lendo, não dá para saber o que foi feito.

2019-07-01 18:54 UTC, juliocesark commented on trabalho-final/JulioCesar.md
> +* Adicionado uma pequena funcionalidade com o repositório [bootstrap-social](https://github.com/lipis/bootstrap-social) referente a redes sociais no projeto calourada-bootstrap ([calourada-bootstrap#
Foi retirado o modal que estava apenas com texto, e adicionado 2 botões para rede sociais ao lado de "contate-me" para que ficasse melhor visualizado na página. E para o desenvolvimento desses botões foi utilizado o repositório [bootstrap-social](https://github.com/lipis/bootstrap-social).

2019-07-02 17:27 UTC, filipesaraiva approved these changes

2019-07-03 00:05 UTC, juliocesark commented
O trabalho está ok então? @filipesaraiva posso preencher o relatório da turma?

2019-07-04 03:03 UTC, gustavopinto requested changes

2019-07-04 03:03 UTC, gustavopinto commented on trabalho-final/JulioCesar.md
> +* Matrícula: 201706840034
Falta o link para as atividades em dupla ao longo da disciplina.

2019-07-04 03:10 UTC, juliocesark commented on trabalho-final/JulioCesar.md
> +* Matrícula: 201706840034
Feito

2019-07-16 10:22 UTC, merged