Create WescleyFontes.md
gustavopinto/tesl pull request #158
Opened 2019-06-22 15:11 UTC by wescley

Criação do arquivo na pasta trabalho final.

2019-06-30 10:00 UTC, wescley commented
Bom dia professor Gustavo @gustavopinto 

Este é o arquivo com as informações do planejamento do projeto final da disciplina TESL que deve ser mantido (PR158).

Reinaldo @reinald28 para conhecimento.

Abraços

2019-07-01 17:09 UTC, filipesaraiva requested changes
Olá @wescley, por favor coloque o relatório seguindo estritamente o modelo solicitado.

2019-07-01 21:58 UTC, wescley commented
Professor Filipe @filipesaraiva 
Boa noite!

Tudo bem?
Fiz o ajuste do arquivo ao modelo solicitado.
Favor verificar se está adequado.

Abraços

2019-07-01 22:05 UTC, wescley commented
> Olá @wescley, por favor coloque o relatório seguindo estritamente o modelo solicitado.

Professor Filipe @filipesaraiva
Boa noite!

Tudo bem?
Fiz o ajuste do arquivo ao modelo solicitado.
Favor verificar se está adequado.

Abraços

2019-07-04 16:36 UTC, filipesaraiva requested changes

2019-07-04 16:36 UTC, filipesaraiva commented on trabalho-final/WescleyFontes.md
> +* Reporte de bug na ferramenta de geração de sites dinâmicos Docusaurus.([BUG1](https://github.com/facebook/docusaurus/issues/1620))
Ainda não está no padrão - você está misturando bugs com docs. Olhe novamente o modelo.

2019-07-04 17:20 UTC, wescley commented on trabalho-final/WescleyFontes.md
> +* Reporte de bug na ferramenta de geração de sites dinâmicos Docusaurus.([BUG1](https://github.com/facebook/docusaurus/issues/1620))
Professor Filipe @filipesaraiva 

Boa tarde!

Verifique se agora está ok.

Abraços

2019-07-04 17:30 UTC, filipesaraiva commented on trabalho-final/WescleyFontes.md
> +* Reporte de bug na ferramenta de geração de sites dinâmicos Docusaurus ao tentar configurar um site.([BUG1](https://github.com/facebook/docusaurus/issues/1620))
Pela discussão no link, esse bug report é inválido.

2019-07-04 17:30 UTC, filipesaraiva commented on trabalho-final/WescleyFontes.md
> +* Melhorar a documentação da ferramenta de geração de sites dinâmicos Nikola em relação ao uso da configuração da linguagem Markdown([DOC1](https://github.com/getnikola/nikola/issues/3268))
Isso aqui pode ser um bug report mas não foi uma melhoria de documentação - foi implementada pelos próprios autores do projeto.

2019-07-04 17:30 UTC, filipesaraiva commented on trabalho-final/WescleyFontes.md
> +* Tradução para o idioma português de partes do Get Starting do Docusaurus ([TR1](https://crowdin.com/translate/docusaurus/2499/en-ptbr))
Essa tradução não está possível de ser acessada.

2019-07-04 17:30 UTC, filipesaraiva commented on trabalho-final/WescleyFontes.md
> +* Tradução para o idioma português de partes do processo de tradução (readme) da ferramenta Brackets([TR2](https://github.com/adobe/brackets/issues/14822))
Essa tradução está como uma issue? Por que não um PR?

2019-07-05 01:17 UTC, wescley commented on trabalho-final/WescleyFontes.md
> +* Reporte de bug na ferramenta de geração de sites dinâmicos Docusaurus ao tentar configurar um site.([BUG1](https://github.com/facebook/docusaurus/issues/1620))
Professor,

Boa tarde!

Ao começar o uso da ferramenta tive certa dificuldade registrei esta issue para a equipe mantenedora.
Em virtude do contexto fiz o registro desta nova issue na ferramenta de limpeza de desktop: OrganiseDesktop, ao se tentar executar a opção "undo" o sistema não funcionou como esperado.([BUG1](https://github.com/blavejr/OrganiseDesktop/issues/70)).

Abraços

2019-07-05 01:17 UTC, wescley commented on trabalho-final/WescleyFontes.md
> +* Melhorar a documentação da ferramenta de geração de sites dinâmicos Nikola em relação ao uso da configuração da linguagem Markdown([DOC1](https://github.com/getnikola/nikola/issues/3268))
Professor,

Boa tarde!

Procede!
Já fiz o ajuste correto para reporte de bug.

Abraços

2019-07-05 01:17 UTC, wescley commented on trabalho-final/WescleyFontes.md
> +* Tradução para o idioma português de partes do Get Starting do Docusaurus ([TR1](https://crowdin.com/translate/docusaurus/2499/en-ptbr))
Professor,
Boa noite!
A tradução está na ferramenta: https://crowdin.com/translate/
Fiz a tradução de alguns trechos do getting started e do ap--comands.

Abraços

2019-07-05 01:17 UTC, wescley commented on trabalho-final/WescleyFontes.md
> +* Tradução para o idioma português de partes do processo de tradução (readme) da ferramenta Brackets([TR2](https://github.com/adobe/brackets/issues/14822))
Professor farei o registro do PR.

2019-07-05 16:59 UTC, filipesaraiva commented on trabalho-final/WescleyFontes.md
> +* Reporte de bug na ferramenta de geração de sites dinâmicos Docusaurus ao tentar configurar um site.([BUG1](https://github.com/facebook/docusaurus/issues/1620))
Agora sim.

2019-07-05 17:01 UTC, filipesaraiva commented on trabalho-final/WescleyFontes.md
> +* Melhorar a documentação da ferramenta de geração de sites dinâmicos Nikola em relação ao uso da configuração da linguagem Markdown([DOC1](https://github.com/getnikola/nikola/issues/3268))
Ok mas agora acabou de surgir outro problema - você ficou com 3 bug reports, e a especificação dessa tarefa limita-a a apenas 2.

2019-07-05 17:02 UTC, filipesaraiva commented on trabalho-final/WescleyFontes.md
> +* Tradução para o idioma português de partes do Get Starting do Docusaurus ([TR1](https://crowdin.com/translate/docusaurus/2499/en-ptbr))
Terei que conferir em sala.

2019-07-05 20:34 UTC, wescley commented on trabalho-final/WescleyFontes.md
> +* Tradução para o idioma português de partes do Get Starting do Docusaurus ([TR1](https://crowdin.com/translate/docusaurus/2499/en-ptbr))
Professor, estou em viagem a Brasília.
Mostro na próxima aula ou mando um print.

2019-07-15 09:12 UTC, merged