projeto final - @cassiobatista
gustavopinto/tesl pull request #159
Opened 2019-06-23 00:05 UTC by cassiobatista

Solves issue #156

2019-06-26 18:30 UTC, gustavopinto commented
Acho que o @cassiobatista quer, de toda forma, se tonar o maior committer do site da disciplina :-)

2019-06-27 23:44 UTC, cassiobatista commented
> Acho que o @cassiobatista quer, de toda forma, se tonar o maior committer do site da disciplina :-)

em minha defesa, tive que resumir e adequar meus textões porque (re?)definiram o template pro relatório final :)

2019-07-04 16:40 UTC, filipesaraiva requested changes
Cassio, pedi algumas alterações para adequar seu relatório ao modelo.

2019-07-04 16:40 UTC, filipesaraiva commented on trabalho-final/CassioBatista.md
> +[Hugo](https://gohugo.io/) (see it on [GitHub](https://github.com/gohugoio/hugo)
Em que pese a explicação ter sido interessante, ela está fora do modelo portanto vou pedir que a remova.

2019-07-04 16:40 UTC, filipesaraiva commented on trabalho-final/CassioBatista.md
> +- theme: Hugo Academic
Coloca seguindo o modelo - só uma linha ou uma descrição curta do que foi feito e link para o PR.

Faça isso nas demais entradas.

2019-07-04 16:53 UTC, cassiobatista commented on trabalho-final/CassioBatista.md
> +- theme: Hugo Academic
done.

2019-07-04 17:20 UTC, filipesaraiva approved these changes

2019-07-04 17:21 UTC, filipesaraiva commented
Massa @cassiobatista, parabéns pelas contribuições! Agora é só criar um PR colocando o que você fez também no relatório geral da turma.

2019-07-04 17:21 UTC, merged