Criar Dupla_ANAISABELA_JOSEPAULO.md
gustavopinto/tesl pull request #16
Opened 2019-04-05 20:36 UTC by anaisabelamr

2019-04-08 10:42 UTC, gustavopinto requested changes
Como mencionei na revisão (veja aqui: https://github.com/gustavopinto/tesl/pull/16/files/e222eb33ef307807e7360fc37a550bad4a507041#diff-43c86d90ca6862bb5fe1e3ca06039cdd), ainda é necessário alterar o arquivo Duplas.md com o link para o arquivo criado.

2019-04-08 10:42 UTC, gustavopinto commented on duplas/Dupla_ANAISABELA_JOSEPAULO.md
> +# Dupla ANAISABELA e JOSEPAULO
Faltou editar o arquivo Duplas.md com o link para esse arquivo.

2019-04-12 18:15 UTC, gustavopinto commented
Ainda pendente, @anaisabelamr.

2019-04-26 21:42 UTC, pauloneves123 commented
@anaisabelamr depois coloca dentro do pull request a atividade 4:
[Atividade 4] https://docs.google.com/document/d/1walNRj8arag4swfNYgPHm4TUPC025MHhKMiBhlxUG9o/edit?usp=sharing

2019-05-03 21:16 UTC, anaisabelamr commented
adicionar link da atividade 5 (https://docs.google.com/document/d/11EaqBYXRBm7bzCgs8JkvTGVZ5b7uIzRFDXR5iXdNo_w/edit?usp=sharing)

obs: nao consegui fazer na hora da aula

2019-07-01 13:44 UTC, closed without merging