[WIP] GuilhermeAlbuquerque.md
gustavopinto/tesl pull request #184
Opened 2019-06-30 04:52 UTC by Lakshamana

2019-07-01 02:00 UTC, filipesaraiva requested changes
Interessantes contribuições! Muito bacana!

2019-07-01 02:00 UTC, filipesaraiva commented on trabalho-final/GuilhermeAlbuquerque.md
> +* Adicão de [página de documentação](https://musescore.org/en/handbook/developers-handbook/compilation/compile-instructions-archlinux-based-distros-git) instruções de instalação de dependências para
Você tem o link para o PR/commit/etc que adicionou essa documentação?

2019-07-01 02:36 UTC, Lakshamana commented on trabalho-final/GuilhermeAlbuquerque.md
> +* Adicão de [página de documentação](https://musescore.org/en/handbook/developers-handbook/compilation/compile-instructions-archlinux-based-distros-git) instruções de instalação de dependências para
Na verdade não, professsor. Ela foi adicionada como wiki em um site separado, próprio do MuseScore

2019-07-01 13:37 UTC, filipesaraiva commented on trabalho-final/GuilhermeAlbuquerque.md
> +* Adicão de [página de documentação](https://musescore.org/en/handbook/developers-handbook/compilation/compile-instructions-archlinux-based-distros-git) instruções de instalação de dependências para
Entendi, mas encontrei [esta página](https://musescore.org/en/user/2221850) por onde consegui confirmar sua autoria :+1:

2019-07-01 13:38 UTC, filipesaraiva approved these changes

2019-07-04 02:59 UTC, merged

2019-07-04 02:59 UTC, gustavopinto commented
Altera agora o arquivo da turma? https://github.com/gustavopinto/tesl/tree/master/trabalho-final