Trabalho final - Uriel Ferreira Campos
gustavopinto/tesl pull request #189
Opened 2019-07-01 22:34 UTC by urielfcampos

closes #164

2019-07-02 01:06 UTC, filipesaraiva requested changes
Boas contribuições. Segue pedidos de alterações.

2019-07-02 01:06 UTC, filipesaraiva commented on duplas/Dupla_URIELCAMPOS_JOAOPEDROMORAES.md
> +## Atividade 12
Seria melhor não ter misturado o Trabalho Final com a Atividade 12 - são 2 trabalhos diferentes. Dividir essas contribuições em dois PRs diferentes.

2019-07-02 01:06 UTC, filipesaraiva commented on trabalho-final/trabalho_final_uriel_campos.md
> +## SUBSEÇÃO DE TAREFA REALIZADA
Tem que escrever o tipo de tarefa realizada. Veja o modelo.

Vi que abaixo você misturou diferentes tarefas. Deve ficar cada uma em uma subseção de 2º nível (`##`).

2019-07-02 01:06 UTC, filipesaraiva commented on trabalho-final/trabalho_final_uriel_campos.md
> +- Um projeto de auxílio para Dungeon masters de rpg de mesa, ele gera cidades e regiões inteiras, uma [issue](https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/issues/205), pedia
Soa como uma grande funcionalidade sim, já que ela pressupõe um maior esforço de desenvolvimento e entrega algo bem diferente do que já tem.

2019-07-02 01:08 UTC, urielfcampos commented on duplas/Dupla_URIELCAMPOS_JOAOPEDROMORAES.md
> +## Atividade 12
Foi um erro meu, que passou no rebase, vou remover. Já temos uma PR aberta com a atividade 12. #186

2019-07-02 01:25 UTC, urielfcampos commented on trabalho-final/trabalho_final_uriel_campos.md
> +## SUBSEÇÃO DE TAREFA REALIZADA
Fiz as modificações professor.

2019-07-02 17:25 UTC, filipesaraiva commented
Solicitações corrigidas, valeu e siga em frente!

2019-07-02 17:25 UTC, filipesaraiva approved these changes

2019-07-03 13:13 UTC, urielfcampos commented
Adicionei minhas  contribuições no relatório da turma.

2019-07-04 03:00 UTC, merged