Criação do arquivo do trabalho final
gustavopinto/tesl pull request #198
Opened 2019-07-03 21:13 UTC by reinald28

Criação do arquivo do trabalho final

2019-07-04 03:03 UTC, gustavopinto requested changes

2019-07-04 03:03 UTC, gustavopinto commented on trabalho-final/trabalho-final - Reinaldo Cardoso.md
> +## SUBSEÇÃO DE TAREFA REALIZADA
Esse header não é necessário

2019-07-04 03:03 UTC, gustavopinto commented on trabalho-final/trabalho-final - Reinaldo Cardoso.md
> +### DESCRIÇÃO CURTA DA TAREFA REALIZADA
Nem esse

2019-07-05 00:52 UTC, reinald28 commented on trabalho-final/trabalho-final - Reinaldo Cardoso.md
> +### DESCRIÇÃO CURTA DA TAREFA REALIZADA
Criei um novo PR com o commit do arquivo modificado. Pois não consegui editar esse aquivo daqui...haha. Vou fechar esse PR.

Att;

2019-07-05 00:52 UTC, closed without merging