Relatório do Trabalho Final - Lucas Monteiro
gustavopinto/tesl pull request #199
Opened 2019-07-03 22:38 UTC by tavareslucas

2019-07-05 16:55 UTC, filipesaraiva commented on trabalho-final/LucasMonteiro.md
> +* Artigo sobre análise quantitativa de testes usando o SonarQube em repositórios do GitHub (Dupla com o @leochrisis, ainda sem link pq não vai dar pra terminar antes de sexta-feira)
O merge desse PR está bloqueado por conta dessa atividade.

2019-07-05 16:56 UTC, filipesaraiva requested changes

2019-07-05 16:56 UTC, filipesaraiva commented on trabalho-final/trabalho-final-turma.md
> +* Tradução do README do projeto scancode-toolkit ([PR](https://github.com/nexB/scancode-toolkit/pull/1640) - [@tavareslucas](https://github.com/tavareslucas))
Como o merge do individual está bloqueado, não há motivo para alterar o relatório da turma. Reverter as mudanças no arquivo de relatório da turma.

2019-07-05 17:17 UTC, tavareslucas commented on trabalho-final/LucasMonteiro.md
> +* Artigo sobre análise quantitativa de testes usando o SonarQube em repositórios do GitHub (Dupla com o @leochrisis, ainda sem link pq não vai dar pra terminar antes de sexta-feira)
Olá professor, o PR ja foi atualizado com o commit do link para o artigo nos dois arquivos (pessoal e da turma), preciso reverter o commit ainda, ou só deixar assim mesmo?

2019-07-15 09:11 UTC, filipesaraiva approved these changes

2019-07-15 09:11 UTC, merged