Adiciona @lubien em trabalho-final-turma.md
gustavopinto/tesl pull request #208
Opened 2019-07-04 03:10 UTC by lubien

2019-07-05 17:05 UTC, filipesaraiva requested changes

2019-07-05 17:05 UTC, filipesaraiva commented on trabalho-final/trabalho-final-turma.md
> +Esse arquivo compila **todas as colaborações*- realizadas pela turma durante a realização do trabalho final.
Essa alteração está errada, não?

2019-07-05 17:51 UTC, lubien commented on trabalho-final/trabalho-final-turma.md
> +Esse arquivo compila **todas as colaborações*- realizadas pela turma durante a realização do trabalho final.
Resolvido

2019-07-15 09:08 UTC, filipesaraiva approved these changes

2019-07-15 09:08 UTC, merged