Atualizando tarefa 2
gustavopinto/tesl pull request #35
Opened 2019-04-05 21:58 UTC by AugustofCravo

Finalizando tarefa 2.

2019-04-08 11:00 UTC, gustavopinto requested changes
@AugustofCravo, há alguns comentários no PR. Por favor, resolva-os.

2019-04-08 11:00 UTC, gustavopinto commented on duplas/DUPLA_AUGUSTOCRAVO_THAYSSÁ
> +- Atividade03: [link aqui](https://docs.google.com/document/d/1E4lbbeLnLmlgngp9UEUp7Jhbp2i7vm_b5nYqVztZqRA/edit?usp=sharing)
Não seria atividade02?

2019-04-08 11:00 UTC, gustavopinto commented on duplas/DUPLA_AUGUSTOCRAVO_THAYSSÁ
> +#Dupla THAYS SÁ e AUGUSTO CRAVO
Falta também editar o arquivos duplas.md para apontar para o arquivo criado.

2019-04-08 11:00 UTC, gustavopinto commented on duplas/DUPLA_AUGUSTOCRAVO_THAYSSÁ
> +#Dupla THAYS SÁ e AUGUSTO CRAVO
Ainda falta vocês alterarem o arquivo Duplas.md com o link para o arquivo criado.

2019-04-08 11:00 UTC, gustavopinto commented on duplas/DUPLA_AUGUSTOCRAVO_THAYSSÁ
> +- Atividade03: [link aqui](https://docs.google.com/document/d/1E4lbbeLnLmlgngp9UEUp7Jhbp2i7vm_b5nYqVztZqRA/edit?usp=sharing)
Essa é a atividade02 e não 03.

2019-04-10 15:20 UTC, AugustofCravo commented
Professor, foram feitas as correções pedidas. Obrigado.

2019-04-10 15:20 UTC, closed without merging