Create Dupla_Reinaldo_Wescley.md
gustavopinto/tesl pull request #4
Opened 2019-04-01 20:28 UTC by wescley

Criação do arquivo de duplas.

2019-04-01 20:32 UTC, wescley reviewed
Inclusão das informações de e-mail e github.

2019-04-04 02:23 UTC, filipesaraiva commented
Faltou adicionar o link para o arquivo criado no arquivo de listagem de duplas, [conforme instruções na página](https://github.com/gustavopinto/tesl/blob/master/Duplas.md).

2019-04-04 02:30 UTC, filipesaraiva requested changes

2019-04-04 02:30 UTC, filipesaraiva commented on duplas/Dupla_Reinaldo_Wescley.md
> +
É necessário colocar o link para a primeira atividade no arquivo, utilizando bullet, como em:

```
* [Atividade 1](link_para_atividade)
```

2019-04-04 02:31 UTC, filipesaraiva requested changes
Faltou adicionar o link para o arquivo criado no arquivo de listagem de duplas, [conforme instruções na página](https://github.com/gustavopinto/tesl/blob/master/Duplas.md).

2019-04-12 18:13 UTC, gustavopinto reviewed
Ainda atrasado, @wescley.

2019-04-12 18:13 UTC, gustavopinto commented on duplas/Dupla_Reinaldo_Wescley.md
> +Duplas
Falta a ''#'' que indica seção.

2019-04-12 18:13 UTC, gustavopinto commented on duplas/Dupla_Reinaldo_Wescley.md
> +    Nome Wescley Fontes (wescley.fontes@gmail.com, https://github.com/wescley/)
Deve estar em bullets

2019-04-12 18:13 UTC, gustavopinto commented on duplas/Dupla_Reinaldo_Wescley.md
> +
Falta também editar o arquivo Duplas.md para apontar para o arquivo criado.

2019-04-12 20:17 UTC, wescley commented
O nosso arquivo foi duplicado pode cancelar este.

2019-04-12 20:17 UTC, closed without merging