Create Dupla_Guilherme_Teoian.md
gustavopinto/tesl pull request #5
Opened 2019-04-02 14:13 UTC by Lakshamana

2019-04-04 02:20 UTC, filipesaraiva commented
Faltou adicionar o link para o arquivo criado no arquivo de listagem de duplas, [conforme instruções na página](https://github.com/gustavopinto/tesl/blob/master/Duplas.md).

2019-04-04 02:30 UTC, filipesaraiva requested changes
Faltou adicionar o link para o arquivo criado no arquivo de listagem de duplas, [conforme instruções na página](https://github.com/gustavopinto/tesl/blob/master/Duplas.md).

2019-04-05 20:48 UTC, Lakshamana commented
O commit para o PR está em #15 .

2019-04-05 20:50 UTC, filipesaraiva commented
Os PRs foram divididos em #5 e #15.

2019-04-05 20:50 UTC, filipesaraiva approved these changes

2019-04-05 20:51 UTC, merged