Atividade 3
gustavopinto/tesl pull request #52
Opened 2019-04-12 21:16 UTC by wescley

@reinald28 para conhecimento.

2019-04-12 21:26 UTC, wescley commented
Reinaldo @reinald28 para conhecimento.

2019-04-26 21:27 UTC, filipesaraiva requested changes

2019-04-26 21:27 UTC, filipesaraiva commented on duplas/Dupla_1_Reinaldo_Cardoso_2_Wescley_Fontes.md
>  ## Atividade 02
Colocar no formato `## Atividade x` e deixar o conteúdo das atividades em cada subseção. Veja arquivos de outras duplas para ter como exemplo.

2019-04-26 21:27 UTC, filipesaraiva commented on duplas/Dupla_1_Reinaldo_Cardoso_2_Wescley_Fontes.md
> +## Atividade 03
Mesmo de cima aqui também.

2019-07-01 13:43 UTC, closed without merging