Update_Dupla_Reinaldo_Cardoso_e_Wescley_Fontes
gustavopinto/tesl pull request #91
Opened 2019-05-10 21:28 UTC by reinald28

Inclusão da atividade 06.

Para conhecimento @wescley

2019-05-10 21:33 UTC, wescley commented
@reinald28 obrigado! 👍

2019-05-17 20:29 UTC, filipesaraiva requested changes

2019-05-17 20:29 UTC, filipesaraiva commented on duplas/Dupla_Reinaldo_Cardoso_2_Wescley_Fontes.md
> +- Encontre 3 exemplos de pedidos de feature ou resolução de bugs que foram implementadas, coloque o link para elas e faça um relatório crítico sobre o fluxo: era bug ou feature? foi iniciado por um u
São 3 exemplos, foi informado apenas 1.

2019-05-17 21:02 UTC, reinald28 commented on duplas/Dupla_Reinaldo_Cardoso_2_Wescley_Fontes.md
> +- Encontre 3 exemplos de pedidos de feature ou resolução de bugs que foram implementadas, coloque o link para elas e faça um relatório crítico sobre o fluxo: era bug ou feature? foi iniciado por um u
Olá. Foi o que deu tempo no horário. Se aina puder posso colocar os outros para complementar a resposta.

2019-07-01 13:42 UTC, closed without merging